export const ALL_DETECTIVES = [
  {
    id: 0,
    name: "Detective Emma Watson",
    email: "e.watson@detectiveagency.com",
    specialization: "Corporate Fraud",
    status: "On Case",
    kyc: "Approved",
    activeCases: 2,
    completedCases: 5,
    rating: 4.8,
    date: "Nov 01, 2025",
    isOnline: true,
    lat: 39.5, lng: -98.35,
    personal: {
      fullName: "Emma Watson", dob: "Apr 15, 1980",
      phone: "+1-555-0109", email: "e.watson@detectiveagency.com",
      address: "123 Wall Street, New York, NY, New York, NY 10001",
      nationality: "American",
      emergencyName: "Alice Johnson", emergencyRelation: "Sister", emergencyPhone: "+1-555-0112",
    },
    professional: {
      licenseNumber: "L123456789", licenseState: "NY",
      licenseExpiry: "Apr 15, 2028", experience: "10 years",
      previousAgency: "ABC Detective Agency",
      education: "Bachelor of Science in Criminal Justice",
      certifications: ["Certified Fraud Examiner"],
      specializations: ["Corporate Fraud", "Financial Investigations"],
      languages: ["English", "Spanish"],
    },
    background: { status: "Cleared", criminalRecord: "No" },
    biography: "Emma Watson is a seasoned detective with over 10 years of experience in corporate fraud investigations. She holds a Bachelor of Science in Criminal Justice and is certified as a Fraud Examiner.",
    documents: [
      { name: "ID_Card.pdf", type: "PDF", uploaded: "Nov 01, 2025", status: "Verified" },
      { name: "License.pdf", type: "PDF", uploaded: "Nov 01, 2025", status: "Verified" },
    ],
    references: [
      { name: "John Doe", role: "Manager", agency: "ABC Detective Agency", phone: "+1-555-010", email: "john.doe@abc.com" },
      { name: "Jane Smith", role: "Supervisor", agency: "XYZ Detective Agency", phone: "+1-555-0111", email: "jane.smith@xyz.com" },
    ],
    cases: [
      { id: "C001", title: "Corporate Embezzlement Investigation", client: "John Smith", status: "insights submitted", priority: "urgent", created: "Jan 15, 2026" },
      { id: "C003", title: "Asset Recovery Investigation", client: "John Smith", status: "report ready", priority: "high", created: "Jan 10, 2026" },
    ],
  },
  {
    id: 1,
    name: "Detective James Bond",
    email: "j.bond@detectiveagency.com",
    specialization: "Personal Investigation",
    status: "On Case",
    kyc: "Approved",
    activeCases: 1,
    completedCases: 3,
    rating: 4.5,
    date: "Nov 05, 2025",
    isOnline: true,
    lat: 51.5074, lng: -0.1278,
    personal: {
      fullName: "James Bond", dob: "Mar 10, 1975",
      phone: "+1-555-0200", email: "j.bond@detectiveagency.com",
      address: "007 Spy Lane, London, UK",
      nationality: "British",
      emergencyName: "M Director", emergencyRelation: "Colleague", emergencyPhone: "+1-555-0201",
    },
    professional: {
      licenseNumber: "L007007007", licenseState: "CA",
      licenseExpiry: "Dec 31, 2027", experience: "15 years",
      previousAgency: "MI6 Agency",
      education: "Bachelor of Arts in Criminology",
      certifications: ["Licensed Private Investigator"],
      specializations: ["Personal Investigation", "Surveillance"],
      languages: ["English", "French"],
    },
    background: { status: "Cleared", criminalRecord: "No" },
    biography: "James Bond is an elite investigator with 15 years of experience in personal investigations and surveillance operations worldwide.",
    documents: [
      { name: "ID_Card.pdf", type: "PDF", uploaded: "Nov 05, 2025", status: "Verified" },
      { name: "License.pdf", type: "PDF", uploaded: "Nov 05, 2025", status: "Verified" },
    ],
    references: [
      { name: "M Director", role: "Director", agency: "MI6 Agency", phone: "+1-555-0202", email: "m@mi6.com" },
      { name: "Q Branch", role: "Tech Lead", agency: "MI6 Agency", phone: "+1-555-0203", email: "q@mi6.com" },
    ],
    cases: [
      { id: "C002", title: "Personal Surveillance Operation", client: "Jane Doe", status: "in progress", priority: "high", created: "Jan 20, 2026" },
    ],
  },
  {
    id: 2,
    name: "Detective Olivia Martinez",
    email: "o.martinez@detectiveagency.com",
    specialization: "Missing Persons",
    status: "Available",
    kyc: "Approved",
    activeCases: 0,
    completedCases: 4,
    rating: 4.7,
    date: "Nov 10, 2025",
    isOnline: true,
    lat: 41.8781, lng: -87.6298,
    personal: {
      fullName: "Olivia Martinez", dob: "Jun 22, 1985",
      phone: "+1-555-0300", email: "o.martinez@detectiveagency.com",
      address: "456 Oak Ave, Chicago, IL 60601",
      nationality: "American",
      emergencyName: "Carlos Martinez", emergencyRelation: "Brother", emergencyPhone: "+1-555-0301",
    },
    professional: {
      licenseNumber: "L987654321", licenseState: "IL",
      licenseExpiry: "Jun 22, 2029", experience: "8 years",
      previousAgency: "Chicago PD",
      education: "Master of Science in Forensic Science",
      certifications: ["Certified Missing Persons Investigator"],
      specializations: ["Missing Persons", "Child Recovery"],
      languages: ["English", "Spanish", "Portuguese"],
    },
    background: { status: "Cleared", criminalRecord: "No" },
    biography: "Olivia Martinez specializes in missing persons cases with 8 years of experience. She holds an MSc in Forensic Science and has successfully resolved over 50 missing persons cases.",
    documents: [
      { name: "ID_Card.pdf", type: "PDF", uploaded: "Nov 10, 2025", status: "Verified" },
      { name: "License.pdf", type: "PDF", uploaded: "Nov 10, 2025", status: "Verified" },
    ],
    references: [
      { name: "Chief Rodriguez", role: "Chief", agency: "Chicago PD", phone: "+1-555-0302", email: "rodriguez@cpd.com" },
      { name: "Dr. Lee", role: "Forensic Expert", agency: "Forensic Lab", phone: "+1-555-0303", email: "lee@forensiclab.com" },
    ],
    cases: [],
  },
  {
    id: 3,
    name: "Detective David Lee",
    email: "d.lee@detectiveagency.com",
    specialization: "Cyber Crime",
    status: "Available",
    kyc: "Approved",
    activeCases: 0,
    completedCases: 2,
    rating: 4.6,
    date: "Nov 15, 2025",
    isOnline: true,
    lat: 37.7749, lng: -122.4194,
    personal: {
      fullName: "David Lee", dob: "Sep 14, 1990",
      phone: "+1-555-0400", email: "d.lee@detectiveagency.com",
      address: "789 Tech Blvd, San Francisco, CA 94105",
      nationality: "American",
      emergencyName: "Susan Lee", emergencyRelation: "Spouse", emergencyPhone: "+1-555-0401",
    },
    professional: {
      licenseNumber: "L555444333", licenseState: "CA",
      licenseExpiry: "Sep 14, 2028", experience: "6 years",
      previousAgency: "FBI Cyber Division",
      education: "Bachelor of Science in Computer Science",
      certifications: ["Certified Ethical Hacker", "CISSP"],
      specializations: ["Cyber Crime", "Digital Forensics"],
      languages: ["English", "Mandarin"],
    },
    background: { status: "Cleared", criminalRecord: "No" },
    biography: "David Lee is a cyber crime specialist with 6 years of experience in digital forensics and cyber investigations. Previously worked with the FBI Cyber Division.",
    documents: [
      { name: "ID_Card.pdf", type: "PDF", uploaded: "Nov 15, 2025", status: "Verified" },
      { name: "License.pdf", type: "PDF", uploaded: "Nov 15, 2025", status: "Verified" },
    ],
    references: [
      { name: "Agent Johnson", role: "Senior Agent", agency: "FBI", phone: "+1-555-0402", email: "johnson@fbi.gov" },
      { name: "Prof. Chen", role: "Professor", agency: "MIT", phone: "+1-555-0403", email: "chen@mit.edu" },
    ],
    cases: [],
  },
  {
    id: 4,
    name: "Detective Sophia Anderson",
    email: "s.anderson@detectiveagency.com",
    specialization: "Insurance Fraud",
    status: "Offline",
    kyc: "Pending",
    activeCases: 0,
    completedCases: 0,
    rating: null,
    date: "Feb 01, 2026",
    isOnline: false,
    lat: 25.7617, lng: -80.1918,
    personal: {
      fullName: "Sophia Anderson", dob: "Sep 10, 1988",
      phone: "+1-555-0125", email: "s.anderson@detectiveagency.com",
      address: "555 Oak Lane, Miami, FL, Miami, FL 33101",
      nationality: "American",
      emergencyName: "Thomas Anderson", emergencyRelation: "Father", emergencyPhone: "+1-555-0128",
    },
    professional: {
      licenseNumber: "L555666777", licenseState: "FL",
      licenseExpiry: "Sep 10, 2027", experience: "5 years",
      previousAgency: "Florida Private Investigations",
      education: "Bachelor of Science in Insurance and Risk Management",
      certifications: ["Certified Fraud Investigator", "Insurance Claims Adjuster License"],
      specializations: ["Insurance Fraud", "Claims Investigation"],
      languages: ["English", "French"],
    },
    background: { status: "Pending", criminalRecord: "No" },
    biography: "Sophia Anderson specializes in insurance fraud investigations with 5 years of experience. She holds certifications in fraud investigation and claims adjustment.",
    documents: [
      { name: "ID_Card.pdf", type: "PDF", uploaded: "Feb 01, 2026", status: "Pending" },
      { name: "License.pdf", type: "PDF", uploaded: "Feb 01, 2026", status: "Pending" },
      { name: "Certification_CFI.pdf", type: "PDF", uploaded: "Feb 01, 2026", status: "Pending" },
    ],
    references: [
      { name: "Michael Roberts", role: "Senior Investigator", agency: "Florida Private Investigations", phone: "+1-555-0126", email: "michael.roberts@fpi.com" },
      { name: "Patricia Williams", role: "Manager", agency: "State Farm Insurance", phone: "+1-555-0127", email: "patricia.williams@statefarm.com" },
    ],
    cases: [],
  },
  {
    id: 5,
    name: "Detective Marcus Thompson",
    email: "m.thompson@detectiveagency.com",
    specialization: "Background Checks",
    status: "Offline",
    kyc: "Pending",
    activeCases: 0,
    completedCases: 0,
    rating: null,
    date: "Feb 02, 2026",
    isOnline: false,
    lat: 29.7604, lng: -95.3698,
    personal: {
      fullName: "Marcus Thompson", dob: "Jan 20, 1992",
      phone: "+1-555-0130", email: "m.thompson@detectiveagency.com",
      address: "88 Pine St, Houston, TX 77001",
      nationality: "American",
      emergencyName: "Linda Thompson", emergencyRelation: "Mother", emergencyPhone: "+1-555-0131",
    },
    professional: {
      licenseNumber: "L888999000", licenseState: "TX",
      licenseExpiry: "Jan 20, 2028", experience: "3 years",
      previousAgency: "Texas Investigations LLC",
      education: "Bachelor of Science in Criminal Justice",
      certifications: ["Certified Background Screener"],
      specializations: ["Background Checks", "Employment Verification"],
      languages: ["English"],
    },
    background: { status: "Pending", criminalRecord: "No" },
    biography: "Marcus Thompson is a background check specialist with 3 years of experience in employment and criminal background screening.",
    documents: [
      { name: "ID_Card.pdf", type: "PDF", uploaded: "Feb 02, 2026", status: "Pending" },
      { name: "License.pdf", type: "PDF", uploaded: "Feb 02, 2026", status: "Pending" },
    ],
    references: [
      { name: "James Carter", role: "Director", agency: "Texas Investigations LLC", phone: "+1-555-0132", email: "j.carter@txinv.com" },
      { name: "Sara Mills", role: "HR Manager", agency: "CorpCheck Inc", phone: "+1-555-0133", email: "s.mills@corpcheck.com" },
    ],
    cases: [],
  },
  {
    id: 6,
    name: "Detective Rachel Kim",
    email: "r.kim@detectiveagency.com",
    specialization: "Surveillance",
    status: "Offline",
    kyc: "Pending",
    activeCases: 0,
    completedCases: 0,
    rating: null,
    date: "Feb 03, 2026",
    isOnline: false,
    lat: 47.6062, lng: -122.3321,
    personal: {
      fullName: "Rachel Kim", dob: "Apr 05, 1995",
      phone: "+1-555-0140", email: "r.kim@detectiveagency.com",
      address: "22 Maple Ave, Seattle, WA 98101",
      nationality: "American",
      emergencyName: "David Kim", emergencyRelation: "Brother", emergencyPhone: "+1-555-0141",
    },
    professional: {
      licenseNumber: "L111222333", licenseState: "WA",
      licenseExpiry: "Apr 05, 2029", experience: "2 years",
      previousAgency: "Pacific Northwest Surveillance",
      education: "Associate Degree in Criminal Justice",
      certifications: ["Licensed Surveillance Investigator"],
      specializations: ["Surveillance", "Covert Operations"],
      languages: ["English", "Korean"],
    },
    background: { status: "Pending", criminalRecord: "No" },
    biography: "Rachel Kim is a surveillance specialist with 2 years of experience in covert operations and field investigations.",
    documents: [
      { name: "ID_Card.pdf", type: "PDF", uploaded: "Feb 03, 2026", status: "Pending" },
      { name: "License.pdf", type: "PDF", uploaded: "Feb 03, 2026", status: "Pending" },
    ],
    references: [
      { name: "Tom Nguyen", role: "Lead Investigator", agency: "Pacific Northwest Surveillance", phone: "+1-555-0142", email: "t.nguyen@pns.com" },
      { name: "Amy Chen", role: "Supervisor", agency: "Seattle PD", phone: "+1-555-0143", email: "a.chen@seattlepd.gov" },
    ],
    cases: [],
  },
];
